### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by jerem1508** [entrepreneur-interet-general/Merge-Machine#25]
```15:26:32 *** Listening on high, low...
16:45:27 low: api_queued_modules._es_linker('8b6a7caa5bca9b326a70f194bd03d699', None, {'must': {}, 'best_thresh': 1, 'non_matching_pairs': [[981, '576'], [981, '611'], [981, '2585'], [190, '1774'], [1234, '1344'], [1234, '2030'], [1234, '4839'], [1234, '397'], [1154, '4813'], [1154, '96'], [1154, '48'], [1154, '163'], [1154, '138']], 'exact_pairs': [[190, '1853'], [85, '4451'], [845, '5955'], [1234, '4964'], [562, '4656'], [462, '4019'], [1038, '2468'], [29, '5406'], [464, '2104'], [1370, '5171'], [313, '2280'], [1229, '1112'], [263, '5040'], [41, '3808'], [702, '1240'], [525, '2616'], [734, '3379'], [238, '5350'], [786, '513'], [867, '3527'], [685, '5904'], [334, '6072'], [1400, '18'], [815, '5091'], [1346, '4159'], [710, '810'], [342, '89'], [19, '2747'], [545, '1562']], 'must_not': {}, 'queries': [{'template': [['must', ['departement'], ['departement'], '.integers', 1.3333333333333333], ['must', ['lycees_sources'], ['denomination_principale_uai', 'patronyme_uai'], '.n_grams', 0.6666666666666666]], 'expected_precision': 1, 'best_thresh': 15.516269, 'thresh': 0, 'expected_recall': 0.9333333333333333}, {'template': [['must', ['departement'], ['departement'], '.integers', 0.75], ['must', ['lycees_sources'], ['denomination_principale_uai', 'patronyme_uai'], '.french', 1.5], ['must', ['lycees_sources'], ['denomination_principale_uai', 'patronyme_uai'], '.n_grams', 0.75]], 'expected_precision': 1, 'best_thresh': 27.568615, 'thresh': 0, 'expected_recall': 0.8666666666666667}, {'template': [['must', ['departement'], ['departement'], '.integers', 1.6], ['must', ['lycees_sources'], ['denomination_principale_uai', 'patronyme_uai'], '.french', 0.4]], 'expected_precision': 1, 'best_thresh': 8.116921, 'thresh': 0, 'expected_recall': 0.8666666666666667}], 'index_name': '607f191094702f3946e6b9674ae2d41b', 'forgotten_pairs': [[981, '6165']]}) (8b6a7caa5bca9b326a70f194bd03d699_es_linker)
{'data_was_transformed': True, 'file_name': 'source.csv', 'module_name': 'es_linker', 'nrows': None, 'columns': ['id_cordee', 'lib_cordee', 'region', 'academie', 'departement', 'commune', 'composante_cordee', 'lycees_sources', 'uai']}
Len og_tab: 1414; Len deduped: 922
WARNING:elasticsearch:GET http://localhost:9200/607f191094702f3946e6b9674ae2d41b/1853/structure [status:404 request:0.007s]
16:45:33 elasticsearch.exceptions.NotFoundError: TransportError(404, '{"_index":"607f191094702f3946e6b9674ae2d41b","_type":"1853","_id":"structure","found":false}')
Traceback (most recent call last):
  File "/home/jerem/.local/lib/python3.5/site-packages/rq/worker.py", line 713, in perform_job
    rv = job.perform()
  File "/home/jerem/.local/lib/python3.5/site-packages/rq/job.py", line 558, in perform
    self._result = self._execute()
  File "/home/jerem/.local/lib/python3.5/site-packages/rq/job.py", line 564, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/jerem/w/Magical/the-magical-csv-merge-machine/merge_machine/api_queued_modules.py", line 148, in _es_linker
    proj.write_data()
  File "/home/jerem/w/Magical/the-magical-csv-merge-machine/merge_machine/abstract_data_project.py", line 566, in write_data
    for i, part_tab in enumerate(self.mem_data):
  File "/home/jerem/w/Magical/the-magical-csv-merge-machine/merge_machine/abstract_data_project.py", line 707, in <genexpr>
    for data in self.mem_data)
  File "/home/jerem/w/Magical/the-magical-csv-merge-machine/merge_machine/abstract_data_project.py", line 669, in run_transform_module
    ['func'](partial_data[valid_columns], params)
  File "/home/jerem/w/Magical/the-magical-csv-merge-machine/merge_machine/es_linker.py", line 14, in es_linker
    source = es_match.es_linker(es, source, params)
  File "/home/jerem/w/Magical2/Merge-Machine/merge_machine/es_match.py", line 313, in es_linker
    full_responses = [es.get(index_name, 'structure', ref_idx) for ref_idx in exact_ref_indices]
  File "/home/jerem/w/Magical2/Merge-Machine/merge_machine/es_match.py", line 313, in <listcomp>
    full_responses = [es.get(index_name, 'structure', ref_idx) for ref_idx in exact_ref_indices]
  File "/home/jerem/.local/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/jerem/.local/lib/python3.5/site-packages/elasticsearch/client/__init__.py", line 409, in get
    doc_type, id), params=params)
  File "/home/jerem/.local/lib/python3.5/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/jerem/.local/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 128, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/jerem/.local/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, '{"_index":"607f191094702f3946e6b9674ae2d41b","_type":"1853","_id":"structure","found":false}')
Traceback (most recent call last):
  File "/home/jerem/.local/lib/python3.5/site-packages/rq/worker.py", line 713, in perform_job
    rv = job.perform()
  File "/home/jerem/.local/lib/python3.5/site-packages/rq/job.py", line 558, in perform
    self._result = self._execute()
  File "/home/jerem/.local/lib/python3.5/site-packages/rq/job.py", line 564, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/jerem/w/Magical/the-magical-csv-merge-machine/merge_machine/api_queued_modules.py", line 148, in _es_linker
    proj.write_data()
  File "/home/jerem/w/Magical/the-magical-csv-merge-machine/merge_machine/abstract_data_project.py", line 566, in write_data
    for i, part_tab in enumerate(self.mem_data):
  File "/home/jerem/w/Magical/the-magical-csv-merge-machine/merge_machine/abstract_data_project.py", line 707, in <genexpr>
    for data in self.mem_data)
  File "/home/jerem/w/Magical/the-magical-csv-merge-machine/merge_machine/abstract_data_project.py", line 669, in run_transform_module
    ['func'](partial_data[valid_columns], params)
  File "/home/jerem/w/Magical/the-magical-csv-merge-machine/merge_machine/es_linker.py", line 14, in es_linker
    source = es_match.es_linker(es, source, params)
  File "/home/jerem/w/Magical2/Merge-Machine/merge_machine/es_match.py", line 313, in es_linker
    full_responses = [es.get(index_name, 'structure', ref_idx) for ref_idx in exact_ref_indices]
  File "/home/jerem/w/Magical2/Merge-Machine/merge_machine/es_match.py", line 313, in <listcomp>
    full_responses = [es.get(index_name, 'structure', ref_idx) for ref_idx in exact_ref_indices]
  File "/home/jerem/.local/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/jerem/.local/lib/python3.5/site-packages/elasticsearch/client/__init__.py", line 409, in get
    doc_type, id), params=params)
  File "/home/jerem/.local/lib/python3.5/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/jerem/.local/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 128, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/jerem/.local/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, '{"_index":"607f191094702f3946e6b9674ae2d41b","_type":"1853","_id":"structure","found":false}')
ERROR:rq.worker:elasticsearch.exceptions.NotFoundError: TransportError(404, '{"_index":"607f191094702f3946e6b9674ae2d41b","_type":"1853","_id":"structure","found":false}')
Traceback (most recent call last):
  File "/home/jerem/.local/lib/python3.5/site-packages/rq/worker.py", line 713, in perform_job
    rv = job.perform()
  File "/home/jerem/.local/lib/python3.5/site-packages/rq/job.py", line 558, in perform
    self._result = self._execute()
  File "/home/jerem/.local/lib/python3.5/site-packages/rq/job.py", line 564, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/jerem/w/Magical/the-magical-csv-merge-machine/merge_machine/api_queued_modules.py", line 148, in _es_linker
    proj.write_data()
  File "/home/jerem/w/Magical/the-magical-csv-merge-machine/merge_machine/abstract_data_project.py", line 566, in write_data
    for i, part_tab in enumerate(self.mem_data):
  File "/home/jerem/w/Magical/the-magical-csv-merge-machine/merge_machine/abstract_data_project.py", line 707, in <genexpr>
    for data in self.mem_data)
  File "/home/jerem/w/Magical/the-magical-csv-merge-machine/merge_machine/abstract_data_project.py", line 669, in run_transform_module
    ['func'](partial_data[valid_columns], params)
  File "/home/jerem/w/Magical/the-magical-csv-merge-machine/merge_machine/es_linker.py", line 14, in es_linker
    source = es_match.es_linker(es, source, params)
  File "/home/jerem/w/Magical2/Merge-Machine/merge_machine/es_match.py", line 313, in es_linker
    full_responses = [es.get(index_name, 'structure', ref_idx) for ref_idx in exact_ref_indices]
  File "/home/jerem/w/Magical2/Merge-Machine/merge_machine/es_match.py", line 313, in <listcomp>
    full_responses = [es.get(index_name, 'structure', ref_idx) for ref_idx in exact_ref_indices]
  File "/home/jerem/.local/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/jerem/.local/lib/python3.5/site-packages/elasticsearch/client/__init__.py", line 409, in get
    doc_type, id), params=params)
  File "/home/jerem/.local/lib/python3.5/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/jerem/.local/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 128, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/jerem/.local/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, '{"_index":"607f191094702f3946e6b9674ae2d41b","_type":"1853","_id":"structure","found":false}')
Traceback (most recent call last):
  File "/home/jerem/.local/lib/python3.5/site-packages/rq/worker.py", line 713, in perform_job
    rv = job.perform()
  File "/home/jerem/.local/lib/python3.5/site-packages/rq/job.py", line 558, in perform
    self._result = self._execute()
  File "/home/jerem/.local/lib/python3.5/site-packages/rq/job.py", line 564, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/jerem/w/Magical/the-magical-csv-merge-machine/merge_machine/api_queued_modules.py", line 148, in _es_linker
    proj.write_data()
  File "/home/jerem/w/Magical/the-magical-csv-merge-machine/merge_machine/abstract_data_project.py", line 566, in write_data
    for i, part_tab in enumerate(self.mem_data):
  File "/home/jerem/w/Magical/the-magical-csv-merge-machine/merge_machine/abstract_data_project.py", line 707, in <genexpr>
    for data in self.mem_data)
  File "/home/jerem/w/Magical/the-magical-csv-merge-machine/merge_machine/abstract_data_project.py", line 669, in run_transform_module
    ['func'](partial_data[valid_columns], params)
  File "/home/jerem/w/Magical/the-magical-csv-merge-machine/merge_machine/es_linker.py", line 14, in es_linker
    source = es_match.es_linker(es, source, params)
  File "/home/jerem/w/Magical2/Merge-Machine/merge_machine/es_match.py", line 313, in es_linker
    full_responses = [es.get(index_name, 'structure', ref_idx) for ref_idx in exact_ref_indices]
  File "/home/jerem/w/Magical2/Merge-Machine/merge_machine/es_match.py", line 313, in <listcomp>
    full_responses = [es.get(index_name, 'structure', ref_idx) for ref_idx in exact_ref_indices]
  File "/home/jerem/.local/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/jerem/.local/lib/python3.5/site-packages/elasticsearch/client/__init__.py", line 409, in get
    doc_type, id), params=params)
  File "/home/jerem/.local/lib/python3.5/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/jerem/.local/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 128, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/jerem/.local/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, '{"_index":"607f191094702f3946e6b9674ae2d41b","_type":"1853","_id":"structure","found":false}')
16:45:33 Moving job to 'failed' queue
WARNING:rq.worker:Moving job to 'failed' queue
16:45:33 Cleaning registries for queue: high
16:45:33 Cleaning registries for queue: low
16:45:33 
16:45:33 *** Listening on high, low...
```

**Comment by Leobouloc** [comment]
Wrong repo
